apiVersion: apps/v1
kind: Deployment
metadata:
  name: momentum-core-deployment
  namespace: app
  labels:
    app: momentum-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momentum-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25% 
  template:
    metadata:
      labels:
        app: momentum-core
    spec:
      serviceAccountName: mcore-auth-role
      terminationGracePeriodSeconds: 30  # Time to wait for graceful shutdown
      initContainers:
      - name: vault-init
        image: asia-south1-docker.pkg.dev/staging-433102/momentum-core/momentum-core:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e

            echo "Updating packages and installing required tools..."
            apt-get update && apt-get install -y curl jq

            VAULT_ADDR="http://vault-internal.vault:8200"
            SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

            echo "Authenticating with Vault..."
            VAULT_RESPONSE=$(curl -s -X POST -H "X-Vault-Request: true" -d "{\"jwt\": \"$SA_TOKEN\", \"role\": \"mcore-role\"}" \
              $VAULT_ADDR/v1/auth/kubernetes/login)

            VAULT_TOKEN=$(echo $VAULT_RESPONSE | jq -r '.auth.client_token')
            if [ -z "$VAULT_TOKEN" ]; then
              echo "Failed to get Vault token."
              exit 1
            fi

            echo "Fetching first secret from Vault..."

            VAULT_SECRET=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/secret/data/mcore)

            SECRET_DATA=$(echo $VAULT_SECRET | jq -r '.data.data')
            if [ -z "$SECRET_DATA" ]; then
              echo "Failed to fetch the first secret."
              exit 1
            fi

            echo "Writing first secret to /app/.env..."
            echo "$SECRET_DATA" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > /app/.env


            echo "Fetching Base64 encoded SA  JSON secret from Vault..."
            SA_JSON_BASE64=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/secret2/data/firebase-sa" | jq -r '.data.data["sa-json"]')

            if [ -z "$SA_JSON_BASE64" ]; then
              echo "Failed to fetch the Base64 encoded secret."
              exit 1
            fi

            echo "This is the fetched Base64 encoded JSON:"
            echo "$SA_JSON_BASE64"

            echo "Writing Base64 encoded JSON to /app/firebase_service_account.txt..."
            echo "$SA_JSON_BASE64" > /app/firebase_service_account.txt

            if [ $? -ne 0 ]; then
              echo "Failed to write the Base64 encoded JSON to file."
              exit 1
            fi

            echo "Base64 encoded JSON has been saved to /app/firebase_service_account.txt"


            echo "Secrets saved to /app/.env and /app/firebase_service_account.txt"

        volumeMounts:
          - name: secret-volume
            mountPath: /app  # Ensure this is mapped correctly
        volumeMounts:
          - name: secret-volume
            mountPath: /app
      containers:
      - name: momentum-core
        image: asia-south1-docker.pkg.dev/staging-433102/momentum-core/momentum-core:latest
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: secret-volume
          mountPath: /app/.env
          subPath: .env
        - name: secret-volume  # Reusing the same volume for different subPaths
          mountPath: /app/firebase_service_account.txt
          subPath: firebase_service_account.txt
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 3  # Customize to make probing faste
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: secret-volume
        emptyDir: {}
