apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer-sa
  namespace: mom-vault
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: mom-vault
#   name: vault-access
# rules:
# - apiGroups: [""]
#   resources: ["pods", "pods/exec", "secrets"]
#   verbs: ["get", "list", "exec"]
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: vault-unsealer-binding
#   namespace: mom-vault
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: vault-access
# subjects:
# - kind: ServiceAccount
#   name: vault-unsealer-sa
#   namespace: mom-vault
