apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcore-auth-role-binding
subjects:
- kind: ServiceAccount
  name: mcore-auth-role
  namespace: pgb-ns
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io