apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: neo4j-db
data:
  NEO4J_dbms_mode: "CORE"
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: "1"
  NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime: "1"
