apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: potpie
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - stage-api.potpie.ai
    secretName: tls-secret
  rules:
    - host: stage-api.potpie.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: potpie-service 
                port:
                  number: 8001